FPS = 30
MAP_TILE_WIDTH = MAP_TILE_HEIGHT = 400
WINDOW_WIDTH = 1680
WINDOW_HEIGHT = 1050

HELICOPTER_COLLISION_RECT_DISTANCE = 100

HELICOPTER_HITPOINTS = 100.00
HELICOPTER_ENERGY = 100.00

BIRD_HITPOINT_REDUCTION = 5
ENERGY_DRAINAGE_CLOUD = 0.2
ENERGY_DRAINAGE_TURBO = 0.2

HITPOINT_RESTORE_RATE = 0.01
ENERGY_CHARGE_RATE = 0.02

N_HUMANS = 50

MAX_HUMANS_BEING_CARRIED = 2

HELICOPTER_SPEED_NORMAL = 9
HELICOPTER_SPEED_TURBO = 15